### ISSUE TITLE
Twilio credentials are exposed as plain text in python script

### ISSUE THREAD

**Issue by Davidportlouis** [aaishikasb/Hack-Empowered#2]
raspberry-pi-code.py has twilio account SID and Auth Token exposed as plain text to secure your credentials [refer twilio docs](https://www.twilio.com/docs/usage/secure-credentials)

**Comment by aaishikasb** [comment]
Hey, thanks for letting us know about this, while we did consider using environment variables, it was making collaboration difficult internally. We eventually chose to not do that as we reset the Auth Token anyways after making the repository public, rendering the credentials pretty much useless. We'll definitely consider following the documentation moving forward. Thanks again!
